### ISSUE TITLE
User-Agent: Get Windows build number from registry

### ISSUE THREAD

**Issue by arthuraraujo-msft** [microsoft/sfs-client#185]
as i mention in another comment, while it's undocumented, it's been there as long as I've been at Windows which is a LONG time....for build info it's probably fine for us to use some variant of:

```PowerShell
$cv = Get-ItemProperty 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion'
'Version {0} (OS Build {1}.{2})' -f $cv.DisplayVersion, $cv.CurrentBuildNumber,$cv.UBR
```

which gives the same value as winver.exe, "Version 23H2 (OS Build 22631.3296)" on my dev box.

likely service team just needs a BuildNumber as that's unique across all windows builds ever, e.g.

* The first Windows 10 build number is 10240
* The last Windows 8.1 build number is 9600
* The last Windows XP build number is 3790

so maybe just send up BuildNumber and architecture ID ?

_Originally posted by @JeffMill in https://github.com/microsoft/sfs-client/pull/182#discussion_r1539738152_

**Comment by JeffMill** [comment]
Check with service / telemetry (the latter is now part of Jerry's team) to see if sending up e.g. "Microsoft-SFSClient/1.0 (Windows 22631; amd64)" as an agent string is sufficient for their needs.

**Comment by arthuraraujo-msft** [comment]
Dropping since there is no need for this at the moment. Offline discussion happened.
