### ISSUE TITLE
Setup.ps1 operation fails on Installing C++ Build Tools if already installed.

### ISSUE THREAD

**Issue by niuxw-msft** [microsoft/sfs-client#197]
**Describe the bug**
Setup.ps1 operation fails on Installing C++ Build Tools if already installed.

![image](https://github.com/microsoft/sfs-client/assets/92482140/15ba5b02-af56-4c2a-937d-352fd2871a87)

**To Reproduce**
1. Run the Setup script '.\scripts\Setup.ps1'
2. See the failure

**Expected behavior**
Should be successful.

**Additional context**
The Visual Studio Enterprise 2022 is already installed on my machine. I recalled that the first time I run the script, a VC Build Tool was installed successfully (It showed in Visual Studio Installer with Visual Studio Enterprise). But I manually deleted the tool as it is duplicated than the Visual Studio Enterprise. I hit the issue after then.

**Comment by arthuraraujo-msft** [comment]
@niuxw-msft could you take a look at this issue?

**Comment by arthuraraujo-msft** [comment]
Had some trouble with this and fixed it. Will be putting up a PR.
