### ISSUE TITLE
Product names with line breaks

### ISSUE THREAD

**Issue by arthuraraujo-msft** [microsoft/sfs-client#99]
Got a `Result code: ConnectionUnexpectedError. Message: URL rejected: Malformed input to a URL function` from the tool when trying to use a product with a line break in the middle. Maybe we can validate this earlier.

**Comment by arthuraraujo-msft** [comment]
I have never seen the host part being escaped/percent-encoded. Does libcurl specifically say that it handles escaped/encoded hostnames? If it doesn't, then the encoded/escaped hostname you provide will be used for DNS lookup and will most likely fail or worse, will resolve to an IP that we don't want (think malicious users squatting on such odd domains).

Perhaps you should just validate the url using libcurl and throw a specific error if that fails. See https://curl.se/libcurl/c/libcurl-url.html.

Also, for encoding/escaping the path/query components, check with SFS service team that they or their http stack (.net?) expects it.

_Originally posted by @shishirb-MSFT in https://github.com/microsoft/sfs-client/pull/166#discussion_r1526996225_
            
I will use this class to properly encode the arguments that appear on the URL.

**Comment by JeffMill** [comment]
related to https://github.com/microsoft/sfs-client/issues/33 ?

**Comment by arthuraraujo-msft** [comment]
Yes!
